#
#
#CFLAGS := -g -std=c11 -O3
#WARNINGS := -Wall -Winline -Wno-deprecated
#INCLUDE := -Ilib -Iexternlibs
#LIBRARIES := -lm -lglfw -framework OpenGL
#
#all: matcap transform tests
#
#matcap: programs/matcap.c
#	clang -o executeable/matcap programs/matcap.c \
#	$(INCLUDE) $(LIBRARIES) $(WARNINGS) $(CFLAGS)
#transform: programs/transform.c
#	clang -o executeable/transform programs/transform.c \
#	$(INCLUDE) $(LIBRARIES) $(WARNINGS) $(CFLAGS)
#tests: testing/tests.c
#	clang -o testing/tests testing/tests.c \
#	$(INCLUDE) $(LIBRARIES) $(WARNINGS) $(CFLAGS)
#
#
#
#clean:
#	rm -rf executeable/*
#	echo clean done
#
#runmatcap:
#	executeable/matcap
#runtransform:
#	executeable/transform
#
#runtests:
#	testing/tests
